name: docs

on:
  push:
    branches:
      - main
      - final_project
      - gpu_branch

  pull_request:
    branches:
      - main
      - final_project
      - gpu_branch

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.16
    
    - name: Set up Python environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install .

    - name: Generate documentation
      run: |
        source venv/bin/activate
        cd docs
        make html
    
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        allow_empty_commit: true