name: tests

on:
  push:
    branches:
      - main
      - final_project
      - gpu_branch

  pull_request:
    branches:
      - main
      - final_project
      - gpu_branch

jobs:
  test:
    name: Testing using pytest
    runs-on: ubuntu-latest
    container:
      image: cupy/cupy:v13.4.0

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        apt-get update && apt-get install -y python3-venv python3-pip cmake

    - name: Install additional dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install .
      shell: bash -e {0}

    - name: Test with pytest
      run: |
        source venv/bin/activate
        mkdir -p build
        cmake -B build -S .
        cd build
        make
        cd ..
        python -m pytest
      shell: bash -e {0}