name: tests

on:
  push:
    branches:
      - main
      - final_project
      - gpu_branch

  pull_request:
    branches:
      - main
      - final_project
      - gpu_branch

jobs:
  test:
    name: Testing using pytest
    runs-on: ubuntu-latest
    container:
      image: cupy/cupy:v13.4.0

    steps:
    - uses: actions/checkout@v3

    - name: Install additional dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install .

    - name: Test with pytest
      run: |
        source venv/bin/activate
        python -m pytest